[2023-06-17 21:37:26,995] {scheduler_job.py:182} INFO - Started process (PID=5107) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:26,998] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:37:26,999] {logging_mixin.py:104} INFO - [2023-06-17 21:37:26,999] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:27,019] {logging_mixin.py:104} INFO - [2023-06-17 21:37:27,015] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:37:27,024] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:27,066] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.075 seconds
[2023-06-17 21:37:37,242] {scheduler_job.py:182} INFO - Started process (PID=5127) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:37,244] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:37:37,245] {logging_mixin.py:104} INFO - [2023-06-17 21:37:37,245] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:37,256] {logging_mixin.py:104} INFO - [2023-06-17 21:37:37,253] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:37:37,257] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:37,273] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.035 seconds
[2023-06-17 21:37:47,450] {scheduler_job.py:182} INFO - Started process (PID=5147) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:47,452] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:37:47,453] {logging_mixin.py:104} INFO - [2023-06-17 21:37:47,453] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:47,463] {logging_mixin.py:104} INFO - [2023-06-17 21:37:47,461] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:37:47,466] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:47,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.035 seconds
[2023-06-17 21:37:57,663] {scheduler_job.py:182} INFO - Started process (PID=5167) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:57,666] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:37:57,668] {logging_mixin.py:104} INFO - [2023-06-17 21:37:57,668] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:57,679] {logging_mixin.py:104} INFO - [2023-06-17 21:37:57,676] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:37:57,682] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:37:57,704] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.045 seconds
[2023-06-17 21:38:07,879] {scheduler_job.py:182} INFO - Started process (PID=5187) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:07,881] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:38:07,883] {logging_mixin.py:104} INFO - [2023-06-17 21:38:07,883] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:07,892] {logging_mixin.py:104} INFO - [2023-06-17 21:38:07,889] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:38:07,894] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:07,910] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.035 seconds
[2023-06-17 21:38:18,086] {scheduler_job.py:182} INFO - Started process (PID=5207) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:18,088] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:38:18,090] {logging_mixin.py:104} INFO - [2023-06-17 21:38:18,090] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:18,098] {logging_mixin.py:104} INFO - [2023-06-17 21:38:18,096] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:38:18,100] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:18,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.033 seconds
[2023-06-17 21:38:28,307] {scheduler_job.py:182} INFO - Started process (PID=5227) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:28,310] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:38:28,312] {logging_mixin.py:104} INFO - [2023-06-17 21:38:28,312] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:28,323] {logging_mixin.py:104} INFO - [2023-06-17 21:38:28,320] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:38:28,326] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:28,348] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.045 seconds
[2023-06-17 21:38:38,518] {scheduler_job.py:182} INFO - Started process (PID=5247) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:38,520] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:38:38,522] {logging_mixin.py:104} INFO - [2023-06-17 21:38:38,522] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:38,530] {logging_mixin.py:104} INFO - [2023-06-17 21:38:38,528] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:38:38,532] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:38,548] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:38:48,726] {scheduler_job.py:182} INFO - Started process (PID=5267) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:48,728] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:38:48,729] {logging_mixin.py:104} INFO - [2023-06-17 21:38:48,729] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:48,738] {logging_mixin.py:104} INFO - [2023-06-17 21:38:48,736] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:38:48,740] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:48,756] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:38:58,936] {scheduler_job.py:182} INFO - Started process (PID=5287) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:58,939] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:38:58,942] {logging_mixin.py:104} INFO - [2023-06-17 21:38:58,942] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:58,953] {logging_mixin.py:104} INFO - [2023-06-17 21:38:58,950] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:38:58,955] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:38:58,976] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.045 seconds
[2023-06-17 21:39:09,150] {scheduler_job.py:182} INFO - Started process (PID=5307) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:09,152] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:39:09,154] {logging_mixin.py:104} INFO - [2023-06-17 21:39:09,154] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:09,163] {logging_mixin.py:104} INFO - [2023-06-17 21:39:09,160] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:39:09,165] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:09,186] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:39:19,366] {scheduler_job.py:182} INFO - Started process (PID=5327) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:19,368] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:39:19,370] {logging_mixin.py:104} INFO - [2023-06-17 21:39:19,370] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:19,378] {logging_mixin.py:104} INFO - [2023-06-17 21:39:19,376] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:39:19,381] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:19,401] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:39:29,576] {scheduler_job.py:182} INFO - Started process (PID=5347) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:29,578] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:39:29,580] {logging_mixin.py:104} INFO - [2023-06-17 21:39:29,580] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:29,590] {logging_mixin.py:104} INFO - [2023-06-17 21:39:29,587] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:39:29,592] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:29,615] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.044 seconds
[2023-06-17 21:39:39,788] {scheduler_job.py:182} INFO - Started process (PID=5367) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:39,790] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:39:39,792] {logging_mixin.py:104} INFO - [2023-06-17 21:39:39,792] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:39,806] {logging_mixin.py:104} INFO - [2023-06-17 21:39:39,802] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:39:39,811] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:39,833] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.050 seconds
[2023-06-17 21:39:50,022] {scheduler_job.py:182} INFO - Started process (PID=5385) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:50,042] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:39:50,045] {logging_mixin.py:104} INFO - [2023-06-17 21:39:50,045] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:50,058] {logging_mixin.py:104} INFO - [2023-06-17 21:39:50,055] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:39:50,062] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:39:50,083] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.065 seconds
[2023-06-17 21:40:00,265] {scheduler_job.py:182} INFO - Started process (PID=5407) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:00,267] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:40:00,269] {logging_mixin.py:104} INFO - [2023-06-17 21:40:00,269] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:00,280] {logging_mixin.py:104} INFO - [2023-06-17 21:40:00,277] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:40:00,283] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:00,306] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.046 seconds
[2023-06-17 21:40:10,479] {scheduler_job.py:182} INFO - Started process (PID=5427) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:10,481] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:40:10,483] {logging_mixin.py:104} INFO - [2023-06-17 21:40:10,483] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:10,492] {logging_mixin.py:104} INFO - [2023-06-17 21:40:10,489] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:40:10,494] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:10,516] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:40:20,774] {scheduler_job.py:182} INFO - Started process (PID=5446) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:20,776] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:40:20,779] {logging_mixin.py:104} INFO - [2023-06-17 21:40:20,779] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:20,794] {logging_mixin.py:104} INFO - [2023-06-17 21:40:20,789] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:40:20,799] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:20,827] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.059 seconds
[2023-06-17 21:40:31,006] {scheduler_job.py:182} INFO - Started process (PID=5467) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:31,009] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:40:31,011] {logging_mixin.py:104} INFO - [2023-06-17 21:40:31,011] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:31,023] {logging_mixin.py:104} INFO - [2023-06-17 21:40:31,020] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:40:31,026] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:31,045] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.043 seconds
[2023-06-17 21:40:41,237] {scheduler_job.py:182} INFO - Started process (PID=5487) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:41,251] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:40:41,269] {logging_mixin.py:104} INFO - [2023-06-17 21:40:41,269] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:41,281] {logging_mixin.py:104} INFO - [2023-06-17 21:40:41,277] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:40:41,283] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:41,301] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.069 seconds
[2023-06-17 21:40:51,485] {scheduler_job.py:182} INFO - Started process (PID=5507) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:51,487] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:40:51,489] {logging_mixin.py:104} INFO - [2023-06-17 21:40:51,489] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:51,499] {logging_mixin.py:104} INFO - [2023-06-17 21:40:51,497] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:40:51,502] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:40:51,522] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:41:01,692] {scheduler_job.py:182} INFO - Started process (PID=5527) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:01,695] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:41:01,697] {logging_mixin.py:104} INFO - [2023-06-17 21:41:01,697] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:01,706] {logging_mixin.py:104} INFO - [2023-06-17 21:41:01,704] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:41:01,709] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:01,728] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:41:11,907] {scheduler_job.py:182} INFO - Started process (PID=5547) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:11,910] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:41:11,912] {logging_mixin.py:104} INFO - [2023-06-17 21:41:11,912] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:11,921] {logging_mixin.py:104} INFO - [2023-06-17 21:41:11,919] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:41:11,925] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:11,944] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:41:22,128] {scheduler_job.py:182} INFO - Started process (PID=5567) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:22,131] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:41:22,133] {logging_mixin.py:104} INFO - [2023-06-17 21:41:22,132] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:22,142] {logging_mixin.py:104} INFO - [2023-06-17 21:41:22,140] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:41:22,145] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:22,164] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:41:32,325] {scheduler_job.py:182} INFO - Started process (PID=5587) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:32,328] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:41:32,330] {logging_mixin.py:104} INFO - [2023-06-17 21:41:32,330] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:32,341] {logging_mixin.py:104} INFO - [2023-06-17 21:41:32,338] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:41:32,344] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:32,364] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.043 seconds
[2023-06-17 21:41:42,545] {scheduler_job.py:182} INFO - Started process (PID=5607) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:42,547] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:41:42,550] {logging_mixin.py:104} INFO - [2023-06-17 21:41:42,549] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:42,559] {logging_mixin.py:104} INFO - [2023-06-17 21:41:42,556] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:41:42,561] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:42,580] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:41:52,765] {scheduler_job.py:182} INFO - Started process (PID=5626) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:52,767] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:41:52,769] {logging_mixin.py:104} INFO - [2023-06-17 21:41:52,768] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:52,778] {logging_mixin.py:104} INFO - [2023-06-17 21:41:52,775] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:41:52,780] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:41:52,800] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:42:02,962] {scheduler_job.py:182} INFO - Started process (PID=5647) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:02,964] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:42:02,966] {logging_mixin.py:104} INFO - [2023-06-17 21:42:02,966] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:02,976] {logging_mixin.py:104} INFO - [2023-06-17 21:42:02,973] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:42:02,979] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:03,000] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.042 seconds
[2023-06-17 21:42:13,186] {scheduler_job.py:182} INFO - Started process (PID=5667) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:13,189] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:42:13,191] {logging_mixin.py:104} INFO - [2023-06-17 21:42:13,191] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:13,202] {logging_mixin.py:104} INFO - [2023-06-17 21:42:13,200] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:42:13,205] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:13,226] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.044 seconds
[2023-06-17 21:42:23,391] {scheduler_job.py:182} INFO - Started process (PID=5687) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:23,393] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:42:23,395] {logging_mixin.py:104} INFO - [2023-06-17 21:42:23,395] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:23,405] {logging_mixin.py:104} INFO - [2023-06-17 21:42:23,402] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:42:23,408] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:23,426] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:42:33,593] {scheduler_job.py:182} INFO - Started process (PID=5707) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:33,596] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:42:33,598] {logging_mixin.py:104} INFO - [2023-06-17 21:42:33,598] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:33,606] {logging_mixin.py:104} INFO - [2023-06-17 21:42:33,604] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:42:33,609] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:33,628] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:42:43,806] {scheduler_job.py:182} INFO - Started process (PID=5727) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:43,808] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:42:43,810] {logging_mixin.py:104} INFO - [2023-06-17 21:42:43,810] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:43,819] {logging_mixin.py:104} INFO - [2023-06-17 21:42:43,817] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:42:43,821] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:43,843] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:42:54,024] {scheduler_job.py:182} INFO - Started process (PID=5747) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:54,026] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:42:54,028] {logging_mixin.py:104} INFO - [2023-06-17 21:42:54,028] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:54,038] {logging_mixin.py:104} INFO - [2023-06-17 21:42:54,035] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:42:54,040] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:42:54,059] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:43:04,229] {scheduler_job.py:182} INFO - Started process (PID=5767) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:04,232] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:43:04,234] {logging_mixin.py:104} INFO - [2023-06-17 21:43:04,234] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:04,243] {logging_mixin.py:104} INFO - [2023-06-17 21:43:04,240] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:43:04,245] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:04,265] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:43:14,447] {scheduler_job.py:182} INFO - Started process (PID=5787) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:14,450] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:43:14,451] {logging_mixin.py:104} INFO - [2023-06-17 21:43:14,451] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:14,461] {logging_mixin.py:104} INFO - [2023-06-17 21:43:14,459] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:43:14,464] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:14,483] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:43:24,668] {scheduler_job.py:182} INFO - Started process (PID=5807) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:24,670] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:43:24,671] {logging_mixin.py:104} INFO - [2023-06-17 21:43:24,671] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:24,681] {logging_mixin.py:104} INFO - [2023-06-17 21:43:24,678] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:43:24,683] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:24,703] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:43:34,865] {scheduler_job.py:182} INFO - Started process (PID=5827) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:34,867] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:43:34,869] {logging_mixin.py:104} INFO - [2023-06-17 21:43:34,869] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:34,880] {logging_mixin.py:104} INFO - [2023-06-17 21:43:34,876] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:43:34,883] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:34,902] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.042 seconds
[2023-06-17 21:43:45,085] {scheduler_job.py:182} INFO - Started process (PID=5847) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:45,087] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:43:45,089] {logging_mixin.py:104} INFO - [2023-06-17 21:43:45,089] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:45,100] {logging_mixin.py:104} INFO - [2023-06-17 21:43:45,097] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:43:45,102] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:45,122] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.042 seconds
[2023-06-17 21:43:55,307] {scheduler_job.py:182} INFO - Started process (PID=5865) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:55,310] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:43:55,312] {logging_mixin.py:104} INFO - [2023-06-17 21:43:55,312] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:55,321] {logging_mixin.py:104} INFO - [2023-06-17 21:43:55,318] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:43:55,324] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:43:55,343] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:44:05,510] {scheduler_job.py:182} INFO - Started process (PID=5887) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:05,513] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:44:05,515] {logging_mixin.py:104} INFO - [2023-06-17 21:44:05,515] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:05,525] {logging_mixin.py:104} INFO - [2023-06-17 21:44:05,522] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:44:05,527] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:05,546] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:44:15,702] {scheduler_job.py:182} INFO - Started process (PID=5907) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:15,704] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:44:15,706] {logging_mixin.py:104} INFO - [2023-06-17 21:44:15,706] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:15,714] {logging_mixin.py:104} INFO - [2023-06-17 21:44:15,711] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:44:15,716] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:15,732] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:44:25,931] {scheduler_job.py:182} INFO - Started process (PID=5927) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:25,935] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:44:25,937] {logging_mixin.py:104} INFO - [2023-06-17 21:44:25,936] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:25,946] {logging_mixin.py:104} INFO - [2023-06-17 21:44:25,944] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:44:25,949] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:25,968] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:44:36,132] {scheduler_job.py:182} INFO - Started process (PID=5947) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:36,134] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:44:36,136] {logging_mixin.py:104} INFO - [2023-06-17 21:44:36,136] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:36,148] {logging_mixin.py:104} INFO - [2023-06-17 21:44:36,145] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:44:36,151] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:36,170] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.042 seconds
[2023-06-17 21:44:46,358] {scheduler_job.py:182} INFO - Started process (PID=5967) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:46,362] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:44:46,365] {logging_mixin.py:104} INFO - [2023-06-17 21:44:46,365] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:46,380] {logging_mixin.py:104} INFO - [2023-06-17 21:44:46,376] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:44:46,383] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:46,403] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.049 seconds
[2023-06-17 21:44:56,592] {scheduler_job.py:182} INFO - Started process (PID=5987) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:56,594] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:44:56,596] {logging_mixin.py:104} INFO - [2023-06-17 21:44:56,595] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:56,605] {logging_mixin.py:104} INFO - [2023-06-17 21:44:56,602] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:44:56,608] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:44:56,626] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:45:06,780] {scheduler_job.py:182} INFO - Started process (PID=6007) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:06,782] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:45:06,783] {logging_mixin.py:104} INFO - [2023-06-17 21:45:06,783] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:06,792] {logging_mixin.py:104} INFO - [2023-06-17 21:45:06,789] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:45:06,795] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:06,810] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.035 seconds
[2023-06-17 21:45:16,988] {scheduler_job.py:182} INFO - Started process (PID=6025) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:16,991] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:45:16,992] {logging_mixin.py:104} INFO - [2023-06-17 21:45:16,992] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:17,001] {logging_mixin.py:104} INFO - [2023-06-17 21:45:16,998] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:45:17,003] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:17,022] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.037 seconds
[2023-06-17 21:45:27,195] {scheduler_job.py:182} INFO - Started process (PID=6047) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:27,197] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:45:27,198] {logging_mixin.py:104} INFO - [2023-06-17 21:45:27,198] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:27,207] {logging_mixin.py:104} INFO - [2023-06-17 21:45:27,204] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:45:27,209] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:27,225] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:45:37,382] {scheduler_job.py:182} INFO - Started process (PID=6067) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:37,384] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:45:37,386] {logging_mixin.py:104} INFO - [2023-06-17 21:45:37,386] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:37,394] {logging_mixin.py:104} INFO - [2023-06-17 21:45:37,392] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:45:37,396] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:37,412] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:45:47,577] {scheduler_job.py:182} INFO - Started process (PID=6087) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:47,579] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:45:47,581] {logging_mixin.py:104} INFO - [2023-06-17 21:45:47,581] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:47,590] {logging_mixin.py:104} INFO - [2023-06-17 21:45:47,587] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:45:47,592] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:47,608] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:45:57,784] {scheduler_job.py:182} INFO - Started process (PID=6107) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:57,787] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:45:57,788] {logging_mixin.py:104} INFO - [2023-06-17 21:45:57,788] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:57,797] {logging_mixin.py:104} INFO - [2023-06-17 21:45:57,795] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:45:57,799] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:45:57,815] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:46:07,969] {scheduler_job.py:182} INFO - Started process (PID=6127) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:07,971] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:46:07,973] {logging_mixin.py:104} INFO - [2023-06-17 21:46:07,973] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:07,981] {logging_mixin.py:104} INFO - [2023-06-17 21:46:07,979] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:46:07,983] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:07,999] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:46:18,173] {scheduler_job.py:182} INFO - Started process (PID=6147) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:18,176] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:46:18,177] {logging_mixin.py:104} INFO - [2023-06-17 21:46:18,177] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:18,187] {logging_mixin.py:104} INFO - [2023-06-17 21:46:18,184] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:46:18,190] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:18,210] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:46:28,393] {scheduler_job.py:182} INFO - Started process (PID=6167) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:28,395] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:46:28,397] {logging_mixin.py:104} INFO - [2023-06-17 21:46:28,397] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:28,407] {logging_mixin.py:104} INFO - [2023-06-17 21:46:28,404] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:46:28,409] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:28,428] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:46:38,614] {scheduler_job.py:182} INFO - Started process (PID=6187) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:38,616] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:46:38,617] {logging_mixin.py:104} INFO - [2023-06-17 21:46:38,617] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:38,626] {logging_mixin.py:104} INFO - [2023-06-17 21:46:38,624] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:46:38,629] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:38,645] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.035 seconds
[2023-06-17 21:46:48,816] {scheduler_job.py:182} INFO - Started process (PID=6207) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:48,818] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:46:48,819] {logging_mixin.py:104} INFO - [2023-06-17 21:46:48,819] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:48,828] {logging_mixin.py:104} INFO - [2023-06-17 21:46:48,826] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:46:48,831] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:48,846] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.034 seconds
[2023-06-17 21:46:59,068] {scheduler_job.py:182} INFO - Started process (PID=6227) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:59,071] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:46:59,073] {logging_mixin.py:104} INFO - [2023-06-17 21:46:59,073] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:59,083] {logging_mixin.py:104} INFO - [2023-06-17 21:46:59,080] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:46:59,085] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:46:59,106] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.043 seconds
[2023-06-17 21:47:09,271] {scheduler_job.py:182} INFO - Started process (PID=6247) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:09,275] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:47:09,277] {logging_mixin.py:104} INFO - [2023-06-17 21:47:09,276] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:09,288] {logging_mixin.py:104} INFO - [2023-06-17 21:47:09,285] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:47:09,291] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:09,312] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.046 seconds
[2023-06-17 21:47:19,493] {scheduler_job.py:182} INFO - Started process (PID=6267) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:19,496] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:47:19,497] {logging_mixin.py:104} INFO - [2023-06-17 21:47:19,497] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:19,506] {logging_mixin.py:104} INFO - [2023-06-17 21:47:19,503] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:47:19,508] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:19,528] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:47:29,747] {scheduler_job.py:182} INFO - Started process (PID=6287) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:29,750] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:47:29,751] {logging_mixin.py:104} INFO - [2023-06-17 21:47:29,751] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:29,761] {logging_mixin.py:104} INFO - [2023-06-17 21:47:29,758] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:47:29,764] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:29,783] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:47:39,963] {scheduler_job.py:182} INFO - Started process (PID=6307) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:39,965] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:47:39,967] {logging_mixin.py:104} INFO - [2023-06-17 21:47:39,967] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:39,978] {logging_mixin.py:104} INFO - [2023-06-17 21:47:39,975] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:47:39,980] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:40,000] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.042 seconds
[2023-06-17 21:47:50,173] {scheduler_job.py:182} INFO - Started process (PID=6327) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:50,176] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:47:50,177] {logging_mixin.py:104} INFO - [2023-06-17 21:47:50,177] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:50,187] {logging_mixin.py:104} INFO - [2023-06-17 21:47:50,184] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:47:50,190] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:47:50,210] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:48:00,395] {scheduler_job.py:182} INFO - Started process (PID=6347) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:00,397] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:48:00,399] {logging_mixin.py:104} INFO - [2023-06-17 21:48:00,399] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:00,409] {logging_mixin.py:104} INFO - [2023-06-17 21:48:00,406] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:48:00,411] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:00,430] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:48:10,594] {scheduler_job.py:182} INFO - Started process (PID=6367) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:10,597] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:48:10,599] {logging_mixin.py:104} INFO - [2023-06-17 21:48:10,599] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:10,610] {logging_mixin.py:104} INFO - [2023-06-17 21:48:10,607] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:48:10,613] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:10,639] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.049 seconds
[2023-06-17 21:48:20,820] {scheduler_job.py:182} INFO - Started process (PID=6387) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:20,822] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:48:20,823] {logging_mixin.py:104} INFO - [2023-06-17 21:48:20,823] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:20,833] {logging_mixin.py:104} INFO - [2023-06-17 21:48:20,830] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:48:20,835] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:20,855] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:48:31,034] {scheduler_job.py:182} INFO - Started process (PID=6406) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:31,036] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:48:31,038] {logging_mixin.py:104} INFO - [2023-06-17 21:48:31,038] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:31,048] {logging_mixin.py:104} INFO - [2023-06-17 21:48:31,045] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:48:31,050] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:31,070] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:48:41,235] {scheduler_job.py:182} INFO - Started process (PID=6427) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:41,237] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:48:41,240] {logging_mixin.py:104} INFO - [2023-06-17 21:48:41,239] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:41,248] {logging_mixin.py:104} INFO - [2023-06-17 21:48:41,246] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:48:41,250] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:41,268] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.037 seconds
[2023-06-17 21:48:51,444] {scheduler_job.py:182} INFO - Started process (PID=6447) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:51,447] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:48:51,448] {logging_mixin.py:104} INFO - [2023-06-17 21:48:51,448] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:51,458] {logging_mixin.py:104} INFO - [2023-06-17 21:48:51,455] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:48:51,460] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:48:51,479] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:49:01,664] {scheduler_job.py:182} INFO - Started process (PID=6467) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:01,666] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:49:01,668] {logging_mixin.py:104} INFO - [2023-06-17 21:49:01,667] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:01,677] {logging_mixin.py:104} INFO - [2023-06-17 21:49:01,674] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:49:01,680] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:01,702] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.042 seconds
[2023-06-17 21:49:11,856] {scheduler_job.py:182} INFO - Started process (PID=6487) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:11,858] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:49:11,860] {logging_mixin.py:104} INFO - [2023-06-17 21:49:11,860] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:11,868] {logging_mixin.py:104} INFO - [2023-06-17 21:49:11,866] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:49:11,870] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:11,888] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.036 seconds
[2023-06-17 21:49:22,063] {scheduler_job.py:182} INFO - Started process (PID=6507) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:22,065] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:49:22,067] {logging_mixin.py:104} INFO - [2023-06-17 21:49:22,067] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:22,076] {logging_mixin.py:104} INFO - [2023-06-17 21:49:22,073] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:49:22,079] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:22,099] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:49:32,279] {scheduler_job.py:182} INFO - Started process (PID=6527) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:32,281] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:49:32,283] {logging_mixin.py:104} INFO - [2023-06-17 21:49:32,283] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:32,294] {logging_mixin.py:104} INFO - [2023-06-17 21:49:32,290] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:49:32,296] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:32,315] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:49:42,481] {scheduler_job.py:182} INFO - Started process (PID=6547) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:42,483] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:49:42,485] {logging_mixin.py:104} INFO - [2023-06-17 21:49:42,485] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:42,494] {logging_mixin.py:104} INFO - [2023-06-17 21:49:42,491] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:49:42,497] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:42,514] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.037 seconds
[2023-06-17 21:49:52,687] {scheduler_job.py:182} INFO - Started process (PID=6567) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:52,690] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:49:52,691] {logging_mixin.py:104} INFO - [2023-06-17 21:49:52,691] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:52,703] {logging_mixin.py:104} INFO - [2023-06-17 21:49:52,700] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:49:52,706] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:49:52,725] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:50:02,909] {scheduler_job.py:182} INFO - Started process (PID=6587) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:02,912] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:50:02,914] {logging_mixin.py:104} INFO - [2023-06-17 21:50:02,914] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:02,923] {logging_mixin.py:104} INFO - [2023-06-17 21:50:02,920] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:50:02,925] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:02,944] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.038 seconds
[2023-06-17 21:50:13,107] {scheduler_job.py:182} INFO - Started process (PID=6607) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:13,111] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:50:13,114] {logging_mixin.py:104} INFO - [2023-06-17 21:50:13,113] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:13,126] {logging_mixin.py:104} INFO - [2023-06-17 21:50:13,123] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:50:13,130] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:13,153] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.051 seconds
[2023-06-17 21:50:23,332] {scheduler_job.py:182} INFO - Started process (PID=6627) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:23,335] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:50:23,337] {logging_mixin.py:104} INFO - [2023-06-17 21:50:23,337] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:23,346] {logging_mixin.py:104} INFO - [2023-06-17 21:50:23,344] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:50:23,349] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:23,367] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.039 seconds
[2023-06-17 21:50:33,552] {scheduler_job.py:182} INFO - Started process (PID=6647) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:33,555] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:50:33,556] {logging_mixin.py:104} INFO - [2023-06-17 21:50:33,556] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:33,566] {logging_mixin.py:104} INFO - [2023-06-17 21:50:33,564] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:50:33,569] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:33,589] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:50:43,758] {scheduler_job.py:182} INFO - Started process (PID=6667) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:43,760] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:50:43,762] {logging_mixin.py:104} INFO - [2023-06-17 21:50:43,761] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:43,770] {logging_mixin.py:104} INFO - [2023-06-17 21:50:43,768] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:50:43,772] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:43,789] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.035 seconds
[2023-06-17 21:50:53,965] {scheduler_job.py:182} INFO - Started process (PID=6687) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:53,967] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:50:53,969] {logging_mixin.py:104} INFO - [2023-06-17 21:50:53,969] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:53,978] {logging_mixin.py:104} INFO - [2023-06-17 21:50:53,975] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:50:53,982] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:50:54,002] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.041 seconds
[2023-06-17 21:51:04,185] {scheduler_job.py:182} INFO - Started process (PID=6707) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:04,187] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:51:04,189] {logging_mixin.py:104} INFO - [2023-06-17 21:51:04,189] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:04,200] {logging_mixin.py:104} INFO - [2023-06-17 21:51:04,196] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/dag_with_catchup_backfill.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_catchup_backfill.py", line 17, in <module>
    schedule_interval="@daily"
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 280, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/helpers.py", line 45, in validate_key
    "dots and underscores exclusively".format(k=k)
airflow.exceptions.AirflowException: The key (Catch-up and backfill DAG) has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-06-17 21:51:04,202] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:04,221] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.040 seconds
[2023-06-17 21:51:14,437] {scheduler_job.py:182} INFO - Started process (PID=6727) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:14,440] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:51:14,442] {logging_mixin.py:104} INFO - [2023-06-17 21:51:14,442] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:14,446] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:14,448] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.015 seconds
[2023-06-17 21:51:24,615] {scheduler_job.py:182} INFO - Started process (PID=6747) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:24,617] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:51:24,619] {logging_mixin.py:104} INFO - [2023-06-17 21:51:24,618] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:24,621] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:24,623] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.012 seconds
[2023-06-17 21:51:34,781] {scheduler_job.py:182} INFO - Started process (PID=6767) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:34,783] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:51:34,784] {logging_mixin.py:104} INFO - [2023-06-17 21:51:34,784] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:34,787] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:34,789] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.012 seconds
[2023-06-17 21:51:44,956] {scheduler_job.py:182} INFO - Started process (PID=6787) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:44,958] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:51:44,959] {logging_mixin.py:104} INFO - [2023-06-17 21:51:44,959] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:44,962] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:44,963] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.010 seconds
[2023-06-17 21:51:55,130] {scheduler_job.py:182} INFO - Started process (PID=6807) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:55,132] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:51:55,134] {logging_mixin.py:104} INFO - [2023-06-17 21:51:55,134] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:55,136] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:51:55,138] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.012 seconds
[2023-06-17 21:52:05,312] {scheduler_job.py:182} INFO - Started process (PID=6827) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:05,314] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:52:05,316] {logging_mixin.py:104} INFO - [2023-06-17 21:52:05,315] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:05,318] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:05,319] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.011 seconds
[2023-06-17 21:52:15,484] {scheduler_job.py:182} INFO - Started process (PID=6847) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:15,486] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:52:15,488] {logging_mixin.py:104} INFO - [2023-06-17 21:52:15,488] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:15,491] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:15,493] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.012 seconds
[2023-06-17 21:52:25,662] {scheduler_job.py:182} INFO - Started process (PID=6867) to work on /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:25,664] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/dag_with_catchup_backfill.py for tasks to queue
[2023-06-17 21:52:25,666] {logging_mixin.py:104} INFO - [2023-06-17 21:52:25,666] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:25,668] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_catchup_backfill.py
[2023-06-17 21:52:25,670] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_with_catchup_backfill.py took 0.012 seconds
